### PR TITLE
Kleine Anpassungen

### LINKED ISSUE #5: False detection of bad pool shape
### Thank you and [esc-now.de](https://esc-now.de/_/zfs-offsite-backup-auf-eine-externe-festplatte/?lang=en) for this pretty script.

I am about to tweak and use it for my purposes.

I am running `TrueNAS on FreeBSD 12.2-RELEASE-p12` . One or two updates ago there was introduced a new ZFS feature upgrade which I decided not to upgrade to. Therefore there is a liitle hint in `zpool status`which looks like this (for every pool with this zfs version):

```
  pool: freenas-boot
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 00:00:50 with 0 errors on Sat Apr 16 03:45:50 2022
config:

	NAME          STATE     READ WRITE CKSUM
	freenas-boot  ONLINE       0     0     0
	  ada0p2      ONLINE       0     0     0

errors: No known data errors
```

Your regex for pool health looks among other things for 'UNAVAIL' and hit the info message. Although the pool is healthy.

Maybe this is an edge case but the following line needs to be tuned a bit to be more precise:

https://github.com/dapuru/zfsbackup/blob/aa60e76ce212de8e82a1d40bc53c2a74331118f4/truenas-poolbackup.sh#L149

A quick but little nasty fix could be

```
zpool status | egrep -i '(DEGRADED|FAULTED|OFFLINE|UNAVAIL|REMOVED|FAIL|DESTROYED|corrupt|cannot|unrecover)' | grep -v "features are unavailable"
```

### LINKED ISSUE #8: Yes to all Option
I got ca. 10 datasets, most of them (especially the iocage) have subdatasets. Some of them are big, some of them are small.

On my initial backup I have to watch and reconnect to the script process for 24 hours because of the questions, if a new folder should be created on the (empty/clean) backup HDD. Because of the childdatasets there are tons of questions over the whole day.

I think the security question is not necessary at initial backups (hdd is clean) nor for childdatasets (if there were data, the parent already wiped it).

I would add an option for the command line to skip any `"No snapshot found"` question.

### PR DESCRIPTION
**Pull request by Pitastic**
Nichts großes... da ich das Skript sehr gut finde, habe ich ein paar kleine Fixes / Erweiterungen gemacht:

- Die Verwendung verschlüsselter Pools ist nun optional
  - bei leerer Keyfile-Option wird der Schritt übersprungen
- Counter für den 60 Sekunden Sleep (ich konnte einfach nicht so lange warten 😉 )
- Hotfix für das fälschliche erkennen eines unsauberen Pools (close #5 )
- Ein paar wenige Tippfehler beseitigt und Whitespaces hinzugefügt
- CLI Option `-y` : Yes To All fragt nicht bei der Erstellung jedes Ordners/Datasets im Backup (close #8 )

### CODE REVIEW

**Review by dapuru — CHANGES_REQUESTED** [review]
Hi Pitastic, thanks for the feedback and the changes, they make perfect sense, and are a great addition. However, please change line 144 - the is a bogus line-break. Thanks a lot, Daniel

**Comment by Pitastic** [comment]
Your welcome. Nice to see your review so fast. I am also working on a more automated devd (moving files in place etc.). I would like to include this into this Pull so I converted the request back to a draft.

Regarding your requested changes:
Could you link the code line please? I haven't found the right line 144 . In my code this is

```
  echo "| ${DATASET} | ${USED} | ${SNAPCOUNT} | ${USEDSNAP} |" >> ${BACKUPLOG}
```
https://github.com/Pitastic/zfsbackup/blob/0681d194ebae3778651dbfa67cedfeb87c0ae161/truenas-poolbackup.sh#L144

**Comment by dapuru** [comment]
> Your welcome. Nice to see your review so fast. I am also working on a more automated devd (moving files in place etc.). I would like to include this into this Pull so I converted the request back to a draft.
> 
> Regarding your requested changes: Could you link the code line please? I haven't found the right line 144 . In my code this is
> 
> ```
>   echo "| ${DATASET} | ${USED} | ${SNAPCOUNT} | ${USEDSNAP} |" >> ${BACKUPLOG}
> ```
> 
> https://github.com/Pitastic/zfsbackup/blob/0681d194ebae3778651dbfa67cedfeb87c0ae161/truenas-poolbackup.sh#L144

https://github.com/Pitastic/zfsbackup/blob/0681d194ebae3778651dbfa67cedfeb87c0ae161/truenas-poolbackup.sh#L150

**Review by dapuru — CHANGES_REQUESTED** [review]
Hi Pitastic,
thanks for the additions, also for correcting the bogus line-break,
One question regarding file truenas-copy-devdconf.sh Could you please explain the line "sed -i'.backup' '/pid-file.*/i \   
 directory "/usr/local/etc/devd";"?
I understand the intention. But what exactly does this line do?
Thanks & regards, Daniel

**Comment by Pitastic** [comment]
### Long Story

Sure. The complete command is:
```
sed -i'.backup' '/pid-file.*/i \
     directory "/usr/local/etc/devd";
' /conf/base/etc/devd.conf
```

The command will be executed in a situation where the systems devd config will **not** look into the user directory `/usr/local/etc/devd` for additional configs (search with the `grep` command before).

sed will edit this systemconfig (`/conf/base/etc/devd.conf`)
- looking for the regex `pid-file.*` which is the entry in the options object right after the config directory listings
- insert the line `[WHITESPACES] directory "/usr/local/etc/devd";` in between the pid-file option and the last directory listing
- moves the original file to `/conf/base/etc/devd.conf.backup` (not optional in this operation on non-gnu sed)

### Short Story

#### Before

```
options {
        directory "/etc/devd";
        pid-file "/var/run/devd.pid";
[...]
}
```

#### After

```
options {
        directory "/etc/devd";
        directory "/usr/local/etc/devd";
        pid-file "/var/run/devd.pid";
[...]
}
```

**Comment by dapuru** [comment]
Ah, ok. The part of "looking for pid-file in /conf/base/etc/devd.conf was not transparent to me. Thanks for clarification and the valuable additions. Will merge soon. ;-)

**Review by dapuru — APPROVED** [review]
Great additions.

**Pull request merged**
